favicon: null
name: NJS
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7331517904531211
  brandStrength: 0.6206313013099134
  lightness: 0.9391426278743893
  brandColors:
    - '#FFFFFF'
    - '#E00C7E'
    - '#F47721'
    - '#5A5A5C'
    - '#D9D9D9'
  rhythmicContrast: 0.7552308270242065
typography_spectrum: 0.4802867
layout_spectrum: 0.4032258
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
