name: NJS
favicon: null
layout_spectrum: 0.35661103622987866
typography_spectrum: 0.5358720899093896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6206313013099134
  lightness: 0.9391426278743893
  saturation: 0.7331517904531211
  rhythmicContrast: 0.7552308270242065
purpose: []
