name: NJS
favicon: null
layout_spectrum: 0.4032258
typography_spectrum: 0.4802867
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: NOT JUST STUDIES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#E00C7E'
    - '#F47721'
    - '#5A5A5C'
    - '#D9D9D9'
  brandStrength: 0.6206313013099134
  lightness: 0.9391426278743893
  saturation: 0.7331517904531211
  rhythmicContrast: 0.7552308270242065
purpose: []
